# Generated by Django 4.0 on 2022-10-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('age', models.IntegerField(blank=True, default=18, null=True)),
                ('street', models.CharField(blank=True, max_length=200, null=True)),
                ('village', models.CharField(blank=True, max_length=200, null=True)),
                ('group_no', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'UserProfile',
                'verbose_name_plural': 'UserProfiles',
            },
        ),
    ]
